name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v1
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
        run: npm install
        run: node index.js
        uses: mikeal/publish-to-github-action@master
        
       
